# Generated by Django 5.0.7 on 2024-07-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='photo',
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.brands_list'),
        ),
    ]
