# Generated by Django 5.0.7 on 2024-07-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_brands_list_remove_brand_photo_alter_brand_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
