# Generated by Django 5.0.7 on 2024-07-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_role'),
    ]

    operations = [
    ]
