# Generated by Django 5.0.7 on 2024-07-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20240725_0639'),
    ]

    operations = [
    ]
